{% set name = "xtensor-io" %}
{% set version = "0.7.0" %}
{% set sha256 = "6dbd8ab214def6222ace451800417b2f9a38b3931c41119403eeeb33e43a8350" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtensor-io/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    # - {{ compiler('cxx') }}
    - toolchain
    - gcc-7  # [linux]
    - cmake
    - openimageio
    - zlib
    - highfive  # [not win]
    - xtensor >=0.19.0,<0.20
    - libsndfile  # [not win]
    - boost  # need to add boost here to grab the latest version necessary for openimageio
  run:
    - zlib
    - xtensor >=0.19.0,<0.20
    - openimageio
    - boost
    - highfive  # [not win]
    - libsndfile  # [not win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image/NPZ input/output for xtensor, the C++ tensor algebra library
  description: This library enables loading of many image formats into xtensor/xarrays and NPZ.
  doc_url: http://xtensor-io.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-io

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
